// Generated by tools/generate_icon_pack.py. DO NOT EDIT.
#ifndef ADQT_GENERATED_SNOW_IMAGE_VIEWER_APP_ICONS_H
#define ADQT_GENERATED_SNOW_IMAGE_VIEWER_APP_ICONS_H

#include "external_icon_pack.h"

namespace snow::image_viewer::icons {

const adqt::icons::ExternalIconPack& pack();
adqt::icons::IconPackRegistrationResult registerWith(adqt::icons::IconRenderer& renderer);
adqt::icons::IconPackRegistrationResult ensureRegistered();

namespace app {
[[nodiscard]] adqt::icons::IconRef ApplicationIcon(const adqt::icons::IconColors& colors = {});
}  // namespace app

namespace outlined {
[[nodiscard]] adqt::icons::IconRef ResizeImage(const adqt::icons::IconColors& colors = {});
}  // namespace outlined

}  // namespace snow::image_viewer::icons

#endif  // ADQT_GENERATED_SNOW_IMAGE_VIEWER_APP_ICONS_H
