// Generated by tools/generate_icon_pack.py. DO NOT EDIT.
#ifndef ADQT_GENERATED_SNOW_DRAW_ENGINE_QT_DRAW_ENGINE_ICONS_H
#define ADQT_GENERATED_SNOW_DRAW_ENGINE_QT_DRAW_ENGINE_ICONS_H

#include "external_icon_pack.h"

namespace snow::draw_engine::icons {

const adqt::icons::ExternalIconPack& pack();
adqt::icons::IconPackRegistrationResult registerWith(adqt::icons::IconRenderer& renderer);
adqt::icons::IconPackRegistrationResult ensureRegistered();

namespace cursor {
[[nodiscard]] adqt::icons::IconRef CornerRadius(const adqt::icons::IconColors& colors = {});
}  // namespace cursor

namespace toolbar {
[[nodiscard]] adqt::icons::IconRef SerialDecrease(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef SerialIncrease(const adqt::icons::IconColors& colors = {});
[[nodiscard]] adqt::icons::IconRef SerialTextFields(const adqt::icons::IconColors& colors = {});
}  // namespace toolbar

}  // namespace snow::draw_engine::icons

#endif  // ADQT_GENERATED_SNOW_DRAW_ENGINE_QT_DRAW_ENGINE_ICONS_H
