#ifndef ADQT_ANTD_ICONS_VERSION_H
#define ADQT_ANTD_ICONS_VERSION_H

#define ADQT_ANTD_ICONS_VERSION_MAJOR 1
#define ADQT_ANTD_ICONS_VERSION_MINOR 0
#define ADQT_ANTD_ICONS_VERSION_PATCH 0

#define ADQT_ANTD_ICONS_VERSION_STR "1.0.0"

#endif  // ADQT_ANTD_ICONS_VERSION_H
