// Generated by tools/generate_icon_pack.py. DO NOT EDIT.
#ifndef ADQT_GENERATED_ANT_DESIGN_QT_WIDGET_ICONS_H
#define ADQT_GENERATED_ANT_DESIGN_QT_WIDGET_ICONS_H

#include "external_icon_pack.h"

namespace adqt::widgets::icons {

const adqt::icons::ExternalIconPack& pack();
adqt::icons::IconPackRegistrationResult registerWith(adqt::icons::IconRenderer& renderer);
adqt::icons::IconPackRegistrationResult ensureRegistered();

namespace twotone {
[[nodiscard]] adqt::icons::IconRef EmptySimple(const adqt::icons::IconColors& colors = {});
}  // namespace twotone

}  // namespace adqt::widgets::icons

#endif  // ADQT_GENERATED_ANT_DESIGN_QT_WIDGET_ICONS_H
